import { SPECTRAL_BAND_DOMAIN } from './spectral-noise.js';
/** SPECTRAL acoustic domains and authored settings. NOT measured tire data. Authority: docs/tire-audio.md. */
/** Sole numeric owner for R/S/Q sound design. Units are explicit; values are provisional. */
export const SPECTRAL_SETTINGS = Object.freeze({
  minRate: SPECTRAL_BAND_DOMAIN.minRate,
  maxRate: SPECTRAL_BAND_DOMAIN.maxRate,
  controlHz: 1000,
  seed: 0x3547ab91,
  rearSeed: 0x691cf37d,
  roadGain: 0.04,
  loadScaleNewtons: 2000,
  roadHalfSpeed: 15,
  roadSpeedExponent: 1.5,
  // Broad wheel-order envelopes, not physical tread modes or a fixed tone per axle.
  roadLowOrder: 4,
  roadHighOrder: 12,
  roadMinimumHz: 35,
  roadBandwidthRatio: 0.8,
  roadTextureOrders: 0.6,
  roadTextureDepth: 0.22,
  roadOutputHz: 900,
  // Full accepted harmonic palette at/above this smoothed excitation; weaker states darken.
  harmonicShapeReference: 0.5,
  squealBaseHz: 1100,
  squealSlipHz: 300,
  squealSlipHalfSpeed: 6,
  squealLongitudinalHz: 120,
  squealBaseBandwidthHz: 50,
  squealSlipBandwidthHz: 20,
  squealBandwidthSlipHalfSpeed: 8,
  squealWheelBandwidthHz: 35,
  squealBandwidthWheelHalfSpeed: 30,
  // S uses the same primitive but broad independent bands, not Q harmonics.
  scrubBands: Object.freeze([
    Object.freeze({ baseHz: 700, slipHz: 300, slipHalfSpeed: 6, bandwidthHz: 900 }),
    Object.freeze({ baseHz: 2600, slipHz: 1000, slipHalfSpeed: 10, bandwidthHz: 2000 }),
  ]),
  scrubTextureMaximumHz: 160,
  attackSeconds: 0.015,
  releaseSeconds: 0.01,
  toneSeconds: 0.02,
  wanderSeconds: 0.15,
  wanderDepth: 0.015,
  powerScaleWatts: 8000,
  directionScaleWatts: 100,
  scrubGain: 0.04,
  squealGain: 0.06,
  harmonicWeights: Object.freeze([0.65, 1, 0.6, 0.28]),
  dcHz: 18,
  outputHz: 8000,
});

/** Forces/speeds drive authored textures; identities are discrete, coefficients follow continuously. */
export const SPECTRAL_TEXTURES = Object.freeze([
  Object.freeze({
    surface: 'ASPHALT',
    roadLow: 0.9,
    roadHigh: 0.18,
    scrubLow: 0.35,
    scrubHigh: 0.65,
    squeal: 1,
    scaleMeters: 0.3,
    depth: 0.08,
  }),
  Object.freeze({
    surface: 'SHOULDER',
    roadLow: 0.85,
    roadHigh: 0.7,
    scrubLow: 0.75,
    scrubHigh: 0.7,
    squeal: 0.3,
    scaleMeters: 0.6,
    depth: 0.4,
  }),
  Object.freeze({
    surface: 'GRASS',
    roadLow: 0.85,
    roadHigh: 0.12,
    scrubLow: 0.6,
    scrubHigh: 0.15,
    squeal: 0,
    scaleMeters: 1.4,
    depth: 0.45,
  }),
  Object.freeze({
    surface: 'DIRT',
    roadLow: 1,
    roadHigh: 0.55,
    scrubLow: 0.95,
    scrubHigh: 0.55,
    squeal: 0,
    scaleMeters: 0.8,
    depth: 0.8,
  }),
  Object.freeze({
    surface: 'SAND',
    roadLow: 0.3,
    roadHigh: 0.8,
    scrubLow: 0.35,
    scrubHigh: 1,
    squeal: 0,
    scaleMeters: 0.12,
    depth: 0.2,
  }),
]);
